name: Rclone Uploader
version: 1.0.2
slug: rclone_uploader
description: Puja fitxers CSV a Google Drive amb rclone
startup: once
boot: manual
init: false
hassio_api: false
homeassistant_api: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
